/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  expires_at: Int8 | null;
  id: Generated<number>;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: number;
}

export interface CreditPurchases {
  amount: number;
  created_at: Generated<Timestamp>;
  credits: number;
  id: Generated<string>;
  status: string;
  stripe_payment_intent_id: string | null;
  stripe_session_id: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Sessions {
  expires: Timestamp;
  id: Generated<number>;
  sessionToken: string;
  userId: number;
}

export interface Subscriptions {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  status: string;
  stripe_current_period_end: Timestamp;
  stripe_price_id: string;
  stripe_subscription_id: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface UsageLogs {
  amount: number;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  reason: string;
  success: boolean;
  user_id: number;
}

export interface Users {
  credits: Generated<number>;
  email: string | null;
  emailVerified: Timestamp | null;
  id: Generated<number>;
  image: string | null;
  name: string | null;
  stripeCustomerId: string | null;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  accounts: Accounts;
  credit_purchases: CreditPurchases;
  sessions: Sessions;
  subscriptions: Subscriptions;
  usage_logs: UsageLogs;
  users: Users;
  verification_token: VerificationToken;
}
